name: Close Pull Requests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Prior
        id: prior
        run: |
          SHOULD_PROCEED=true
          echo "should_proceed=$SHOULD_PROCEED" >> $GITHUB_OUTPUT

      - name: Next
        if: ${{ steps.prior.outputs.should_proceed == 'true' }}
        run: |
          echo "Proceeding"

      - name: Close PRs
        run: |
          ACTIVE_PRS=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/search/issues?q=is:pr+is:open+label:%22translation+sync%22+repo:mindaras/github-pr-automation | jq 'if (.total_count > 0) then .items else empty end')
          for row in $(echo "${ACTIVE_PRS}" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${row} | base64 --decode | jq -r ${1}
            }

            ACTIVE_PR_NUMBER=$(_jq '.number')
            ACTIVE_PR_BRANCH_NAME=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/mindaras/github-pr-automation/pulls/$ACTIVE_PR_NUMBER | jq '.head.ref')
            ACTIVE_PR_BRANCH_NAME="${ACTIVE_PR_BRANCH_NAME%\"}"
            ACTIVE_PR_BRANCH_NAME="${ACTIVE_PR_BRANCH_NAME#\"}"
            curl -s -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/mindaras/github-pr-automation/git/refs/heads/$ACTIVE_PR_BRANCH_NAME
            echo "Deleted branch $ACTIVE_PR_BRANCH_NAME"
          done
